"""Tests for SVG utility functions."""

from cardforge.assets.svg_utils import (
    escape_xml,
    sanitize_svg_id,
    svg_header,
    svg_footer,
    svg_rect,
    svg_text,
    svg_image,
    svg_group,
    svg_comment,
)


class TestEscapeXml:
    def test_escapes_ampersand(self):
        assert escape_xml("A & B") == "A &amp; B"

    def test_escapes_lt_gt(self):
        assert escape_xml("<tag>") == "&lt;tag&gt;"

    def test_escapes_quotes(self):
        result = escape_xml('"hello"')
        assert "&quot;" in result

    def test_plain_text_unchanged(self):
        assert escape_xml("hello") == "hello"


class TestSanitizeSvgId:
    def test_replaces_spaces(self):
        assert sanitize_svg_id("my feature id") == "my-feature-id"

    def test_replaces_special_chars(self):
        assert sanitize_svg_id("feat#1!") == "feat-1-"

    def test_lowercases(self):
        assert sanitize_svg_id("MY-ID") == "my-id"

    def test_empty_returns_default(self):
        assert sanitize_svg_id("!!!") == "id"


class TestSvgHeader:
    def test_header_with_mm(self):
        h = svg_header(85, 54)
        assert 'width="85mm"' in h
        assert 'height="54mm"' in h
        assert 'viewBox="0 0 85 54"' in h
        assert h.startswith("<svg")

    def test_header_with_custom_viewbox(self):
        h = svg_header(100, 50, "0 0 200 100")
        assert 'viewBox="0 0 200 100"' in h

    def test_footer(self):
        assert svg_footer() == "</svg>"


class TestSvgRect:
    def test_basic_rect(self):
        r = svg_rect(10, 20, 100, 50)
        assert r.startswith("<rect")
        assert 'x="10"' in r
        assert 'y="20"' in r
        assert 'width="100"' in r
        assert 'height="50"' in r
        assert "/>" in r

    def test_rect_with_fill(self):
        r = svg_rect(0, 0, 10, 10, fill="#ff0000")
        assert 'fill="#ff0000"' in r

    def test_rect_with_stroke(self):
        r = svg_rect(0, 0, 10, 10, stroke="black", stroke_width=1.5)
        assert 'stroke="black"' in r
        assert 'stroke-width="1.5"' in r

    def test_rect_with_rx(self):
        r = svg_rect(0, 0, 100, 50, rx=4)
        assert 'rx="4"' in r

    def test_rect_with_class(self):
        r = svg_rect(0, 0, 10, 10, class_name="card-base")
        assert 'class="card-base"' in r


class TestSvgText:
    def test_basic_text(self):
        t = svg_text(10, 20, "Hello", font_size=3.2)
        assert "<text" in t
        assert "Hello</text>" in t
        assert 'font-size="3.2"' in t

    def test_text_with_fill(self):
        t = svg_text(10, 20, "Hi", fill="white")
        assert 'fill="white"' in t

    def test_text_with_anchor(self):
        t = svg_text(10, 20, "Centered", text_anchor="middle")
        assert 'text-anchor="middle"' in t

    def test_text_escapes_xml(self):
        t = svg_text(0, 0, "A & B < C")
        assert "&amp;" in t
        assert "&lt;" in t


class TestSvgImage:
    def test_basic_image(self):
        i = svg_image(10, 20, 24, 24, "../assets/qr.svg")
        assert "<image" in i
        assert 'href="../assets/qr.svg"' in i
        assert 'width="24"' in i
        assert 'height="24"' in i


class TestSvgGroup:
    def test_empty_group(self):
        g = svg_group()
        assert g == "<g></g>"

    def test_group_with_children(self):
        g = svg_group(children='<rect x="0" y="0" width="10" height="10"/>')
        assert "<rect" in g

    def test_group_with_transform(self):
        g = svg_group(transform="rotate(-25)")
        assert 'transform="rotate(-25)"' in g

    def test_group_with_id(self):
        g = svg_group(id="My Feature!")
        assert 'id="my-feature-"' in g


class TestSvgComment:
    def test_comment(self):
        c = svg_comment("Generated by CardForge")
        assert "<!--" in c
        assert "-->" in c
        assert "CardForge" in c
