"""Print README generator — creates README_PRINT.md for print-ready exports."""

from datetime import datetime
from pathlib import Path

from cardforge.manufacturing.report import ManufacturingReport


def generate_print_readme(
    document_name: str,
    report: ManufacturingReport,
    stl_paths: list,
    output_path: Path,
) -> Path:
    """Generate a print-ready README with instructions.

    Args:
        document_name: Name of the project/document.
        report: Manufacturing analysis report.
        stl_paths: List of generated STL file paths.
        output_path: Where to write the README.

    Returns:
        The output path.
    """
    lines = []
    lines.append(f"# {document_name} — Print-Ready Export")
    lines.append("")
    lines.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    lines.append("")

    # Profile
    p = report.profile
    lines.append("## Manufacturing Profile")
    lines.append("")
    lines.append(f"- **Process:** {p.process.upper()}")
    lines.append(f"- **Nozzle:** {p.nozzle}mm")
    lines.append(f"- **Layer Height:** {p.layer_height}mm")
    lines.append(f"- **Material:** {p.material}")
    lines.append("")

    # Score
    lines.append("## Manufacturability")
    lines.append("")
    lines.append(f"**Score:** {report.score}/100 — {report.score_label}")
    lines.append("")

    if report.warnings:
        lines.append("### Warnings")
        lines.append("")
        for w in report.warnings:
            lines.append(f"- {w.message}")
        lines.append("")

    if report.suggestions:
        lines.append("### Suggestions")
        lines.append("")
        for s in report.suggestions:
            lines.append(f"- {s}")
        lines.append("")

    # STL files
    lines.append("## STL Files")
    lines.append("")
    for sp in stl_paths:
        size_kb = sp.stat().st_size / 1024 if sp.exists() else 0
        lines.append(f"- `{sp.name}` ({size_kb:.0f} KB)")
    lines.append("")

    # Multi-color instructions
    if len(stl_paths) > 1:
        lines.append("## Multi-Color Printing")
        lines.append("")
        lines.append("This export includes separate STL files for each material.")
        lines.append("To print in multiple colors:")
        lines.append("")
        lines.append("### Bambu Studio / OrcaSlicer")
        lines.append("1. Import all STL files together")
        lines.append('2. Select "Yes" when asked if files are a single object with multiple parts')
        lines.append("3. Assign each part to a different filament in the Objects panel")
        lines.append("")
        lines.append("### PrusaSlicer")
        lines.append("1. Import all STL files together")
        lines.append("2. Right-click → Split to parts")
        lines.append("3. Assign extruders per part")
        lines.append("")

    # Print settings
    lines.append("## Recommended Print Settings")
    lines.append("")
    lines.append("```")
    lines.append(f"Nozzle: {p.nozzle}mm")
    lines.append(f"Layer Height: {p.layer_height}mm")
    lines.append(f"Material: {p.material}")
    lines.append("Wall Count: 3")
    lines.append("Top/Bottom Layers: 4")
    lines.append("Infill: 15% grid or gyroid")
    lines.append("Brim: 2mm (recommended for small objects)")
    lines.append("```")
    lines.append("")
    lines.append("---")
    lines.append(f"*Generated by CardForge*")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines))
    return output_path
